env:
  browser: false
  node: true
  commonjs: true
  es6: true
  mocha: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent: ["error", 2]
  no-underscore-dangle: 0
